### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by moh1122** [SilverMarcs/GPTalks#18]
Can I know where to add the API Keys.
I found in Providor folder but its not working im still getting this error message:
`Error: APIErrorResponse(error: OpenAI.APIError(message: "You didn\'t provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you\'re accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.", type: "invalid_request_error", param: nil, code: nil))`

**Comment by SilverMarcs** [comment]
Are you trying to hardcode the api key?

Ideally you should go into settings, go to Provider settings in there, select your provider (OpenAI) and put your API Key there

**Comment by moh1122** [comment]
yup how can I hardcode it.
I checked it in settings and its awesome

**Comment by SilverMarcs** [comment]
Glad to hear it works now.

If you really want to hardcode, perhaps check GPTalks > LLM > Provider.swift and replace the apiKey field with your api key. But this will take effect only for new providers you add since the existing ones were already created with an empty API Key.
But really, you should not consider this option since every provider needs its own API Keys
